# Generated by Django 5.2.1 on 2025-05-26 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('packaging', 'Mua bao bì'), ('maintenance', 'Bảo dưỡng máy'), ('fertilizer', 'Mua phân bón')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.CharField(choices=[('submitted', 'Đã gửi'), ('manager_approved', 'Trưởng bộ phận duyệt'), ('accountant_approved', 'Kế toán duyệt'), ('director_approved', 'Giám đốc duyệt'), ('rejected', 'Từ chối'), ('edit_required', 'Yêu cầu chỉnh sửa')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('accountant_comment', models.TextField(blank=True, null=True)),
                ('director_comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
