# Generated by Django 5.2.1 on 2025-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_editpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='content',
            field=models.TextField(default='Không có chi tiết', verbose_name='Nội dung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='detail',
            field=models.CharField(default='Không có nội dung', max_length=255, verbose_name='Chi tiết'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá'),
            preserve_default=False,
        ),
    ]
