# Generated by Django 5.2.1 on 2025-06-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_expenserequest_content_expenserequest_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='amount',
        ),
    ]
